### ISSUE TITLE
Promoter Testing

### ISSUE THREAD

**Issue by andyhull** [postcode/senoia#101]
Taks for promoter QA:
- Can sign into the site
- Can see a list of their plans
- Can create a new plan
- Can add collaborators to a plan
- Can add operational periods
- Can add multiple assets
- Can assign providers to specific assets
- Can submit a plan
- Can comment on a plan in review
- Receives email when comments are made
- Can view their plans under review
- Can view approved plans

**Comment by hampelm** [comment]
- [x] Can sign into the site
- [x] Can see a list of their plans
- [x] Can create a new plan
- [x] Can add collaborators to a plan - see #114 
- [x] Can add operational periods
- [x] Can add multiple assets
- [x] Can assign providers to specific assets - admin can't create providers; see #149
- [x] Can submit a plan - error submitting; see #122
- [ ] Can comment on a plan in review
- [ ] Receives email when comments are made
- [x] Can view their plans under review
- [x] Can view approved plans

**Comment by hampelm** [comment]
@andyhull: #122 is blocking more testing on this

**Comment by cjlim2007** [comment]
- [x] Can sign into the site
- [x] Can see a list of their plans
- [x] Can create a new plan
- [x] Can add collaborators to a plan
- [x] Can add operational periods
- [x] Can add multiple assets
- [x] Can assign providers to specific assets
- [x] Can submit a plan
- [x] Can comment on a plan in review
- [x] Receives email when comments are made
- [x] Can view their plans under review
- [x] Can view approved plans
